name: Ruby

on:
    push:
        branches: ["develop", "main"]
    pull_request:
        branches: ["develop", "main"]

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                ruby-version: ["3.0"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.0

            - name: Install dependencies
              run: bundle install

            - name: Run RSpec tests
              run: bundle exec rspec
